name: Python application

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest tests.py

    - name: Create ZIP
      run: |
        zip -r uno.zip ./*.py -x "tests.py" "requirements.txt"
    
    - name: Set Git Tag
      id: tag_version
      run: |
        LATEST_TAG=$(git tag -l 'v[0-9]*.0' --sort=-v:refname | head -n 1 || echo "v0.0")
        MAJOR_VERSION=$(echo "$LATEST_TAG" | sed -E 's/v([0-9]+)\.0/\1/')
        
        NEW_VERSION=$((MAJOR_VERSION + 1))
        TAG_NAME="v$NEW_VERSION.0"
        
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: Release ${{ env.TAG_NAME }}
        files: ./uno.zip
